In [1]:
import torch

torch.cuda.is_available()

True

In [2]:
torch.__version__

'2.8.0+cu126'

In [3]:
torch.tensor(5)

tensor(5)

In [4]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [5]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
data = [1, 2, 3, 4, 5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [9]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [ ]:
torch.ones(3, 5)

'torch.FloatTensor'

In [ ]:
torch.ones(512,512)     # 이미지 1이면 흰색, 0이면 검정색

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [13]:
torch.zeros(512, 512)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [14]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
data = torch.rand(3, 3, 3)
data

tensor([[[0.6746, 0.0602, 0.3004],
         [0.6580, 0.2534, 0.0187],
         [0.6480, 0.7254, 0.5801]],

        [[0.7098, 0.6605, 0.6556],
         [0.9554, 0.1894, 0.3529],
         [0.2358, 0.5100, 0.8942]],

        [[0.8173, 0.7142, 0.0127],
         [0.5301, 0.7940, 0.6303],
         [0.1816, 0.0450, 0.9315]]])

In [17]:
data.view(9, 3)

tensor([[0.6746, 0.0602, 0.3004],
        [0.6580, 0.2534, 0.0187],
        [0.6480, 0.7254, 0.5801],
        [0.7098, 0.6605, 0.6556],
        [0.9554, 0.1894, 0.3529],
        [0.2358, 0.5100, 0.8942],
        [0.8173, 0.7142, 0.0127],
        [0.5301, 0.7940, 0.6303],
        [0.1816, 0.0450, 0.9315]])

In [18]:
data.shape

torch.Size([3, 3, 3])

In [19]:
data.dim()

3

In [20]:
data.dtype

torch.float32

In [27]:
torch.cuda.device_count()

1

In [28]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [29]:
device = torch.device('cuda:1')
device

device(type='cuda', index=1)

In [30]:
data = torch.tensor([1, 2, 3])
data

tensor([1, 2, 3])

In [32]:
data.to('cuda')

tensor([1, 2, 3], device='cuda:0')

In [46]:
data1 = torch.tensor([1, 2, 3]).cuda()
data1

tensor([1, 2, 3], device='cuda:0')

In [ ]:
data1.to('cpu')

In [48]:
data = data.to('cuda')
data + data1

tensor([2, 4, 6], device='cuda:0')

In [51]:
data.min(dim= 0)

torch.return_types.min(
values=tensor(1, device='cuda:0'),
indices=tensor(0, device='cuda:0'))

In [52]:
data.dtype

torch.int64

In [53]:
data = data.type(torch.float)
data

tensor([1., 2., 3.], device='cuda:0')

In [54]:
data.dtype

torch.float32

In [55]:
data.mean()

tensor(2., device='cuda:0')

In [60]:
image = torch.rand(3, 128, 128)
image = image.view(1, 3, 128, 128)
image.dim()

4

In [69]:
image = torch.rand(3, 128, 128)
image = image.unsqueeze(dim= 0)     # unsqueeze는 차원을 늘려준다.

In [70]:
image.shape

torch.Size([1, 3, 128, 128])

In [ ]:
data = torch.rand(1, 128, 128)
data = data.squeeze() 
data.shape

torch.Size([128, 128])