In [1]:
import torch

torch.cuda.is_available()

True

In [2]:
torch.__version__

'2.8.0+cu126'

In [3]:
torch.tensor(5)

tensor(5)

In [4]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [8]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
data = [1, 2, 3, 4, 5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [10]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [11]:
torch.ones(3)

tensor([1., 1., 1.])

In [12]:
torch.ones(3, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
torch.ones(512, 512)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [14]:
torch.zeros(512, 512)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.]])

In [18]:
data = torch.rand(3, 3, 3)
data

tensor([[[0.5882, 0.3452, 0.1413],
         [0.7131, 0.7551, 0.7909],
         [0.5036, 0.4747, 0.9701]],

        [[0.0771, 0.3741, 0.3491],
         [0.1825, 0.4345, 0.2483],
         [0.5923, 0.8693, 0.0993]],

        [[0.3263, 0.8750, 0.1493],
         [0.0353, 0.2993, 0.9460],
         [0.5152, 0.5557, 0.8469]]])

In [19]:
data.dim()

3

In [20]:
data.view(9, 3)

tensor([[0.5882, 0.3452, 0.1413],
        [0.7131, 0.7551, 0.7909],
        [0.5036, 0.4747, 0.9701],
        [0.0771, 0.3741, 0.3491],
        [0.1825, 0.4345, 0.2483],
        [0.5923, 0.8693, 0.0993],
        [0.3263, 0.8750, 0.1493],
        [0.0353, 0.2993, 0.9460],
        [0.5152, 0.5557, 0.8469]])

In [22]:
data.view(27)

tensor([0.5882, 0.3452, 0.1413, 0.7131, 0.7551, 0.7909, 0.5036, 0.4747, 0.9701,
        0.0771, 0.3741, 0.3491, 0.1825, 0.4345, 0.2483, 0.5923, 0.8693, 0.0993,
        0.3263, 0.8750, 0.1493, 0.0353, 0.2993, 0.9460, 0.5152, 0.5557, 0.8469])

In [23]:
data.view(3, 9)

tensor([[0.5882, 0.3452, 0.1413, 0.7131, 0.7551, 0.7909, 0.5036, 0.4747, 0.9701],
        [0.0771, 0.3741, 0.3491, 0.1825, 0.4345, 0.2483, 0.5923, 0.8693, 0.0993],
        [0.3263, 0.8750, 0.1493, 0.0353, 0.2993, 0.9460, 0.5152, 0.5557, 0.8469]])

In [24]:
data.view(9, -1)       # -1은 차원을 자동 계산하라는 의미

tensor([[0.5882, 0.3452, 0.1413],
        [0.7131, 0.7551, 0.7909],
        [0.5036, 0.4747, 0.9701],
        [0.0771, 0.3741, 0.3491],
        [0.1825, 0.4345, 0.2483],
        [0.5923, 0.8693, 0.0993],
        [0.3263, 0.8750, 0.1493],
        [0.0353, 0.2993, 0.9460],
        [0.5152, 0.5557, 0.8469]])

In [25]:
data.view(-1)

tensor([0.5882, 0.3452, 0.1413, 0.7131, 0.7551, 0.7909, 0.5036, 0.4747, 0.9701,
        0.0771, 0.3741, 0.3491, 0.1825, 0.4345, 0.2483, 0.5923, 0.8693, 0.0993,
        0.3263, 0.8750, 0.1493, 0.0353, 0.2993, 0.9460, 0.5152, 0.5557, 0.8469])

In [26]:
data.shape

torch.Size([3, 3, 3])

In [28]:
data.dim()

3

In [29]:
data.dtype

torch.float32

In [30]:
torch.cuda.is_available()       # GPU 사용 가능 여부를 확인한다

True

In [32]:
torch.cuda.device_count()       # GPU 갯수 확인

1

In [36]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [40]:
device = torch.device('cuda:1')
device

device(type='cuda', index=1)

In [41]:
data = torch.tensor([1, 2, 3])
data

tensor([1, 2, 3])

In [54]:
data.to('cuda')

tensor([1, 2, 3], device='cuda:0')

In [43]:
data1 = torch.tensor([1, 2, 3]).cuda()
data1

tensor([1, 2, 3], device='cuda:0')

In [53]:
data1.to('cpu')

tensor([1, 2, 3], device='cuda:0')

In [52]:
data

tensor([1, 2, 3])

In [51]:
data1

tensor([1, 2, 3], device='cuda:0')

In [55]:
data = data.to('cuda')
data + data1

tensor([2, 4, 6], device='cuda:0')

In [56]:
data - data1

tensor([0, 0, 0], device='cuda:0')

In [57]:
data * data1

tensor([1, 4, 9], device='cuda:0')

In [58]:
data / data1

tensor([1., 1., 1.], device='cuda:0')

In [59]:
data = torch.tensor([[1, 2, 3], [4, 5, 6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [61]:
data.min()

tensor(1)

In [62]:
data.max()

tensor(6)

In [63]:
data.max(dim= 0)

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))

In [64]:
data.max(dim= 1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))