In [71]:
import pandas as pd
df = pd.read_csv('../data/boston.csv')
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [74]:
import torch

X_train = df.iloc[:, :13].values
# X_train = torch.tensor(X_train)
X_train = torch.FloatTensor(X_train)

y_train = df.iloc[:, -1].values
y_train = torch.FloatTensor(y_train)

In [90]:
import torch.nn as nn
from torch.optim.adam import Adam

model = nn.Sequential(
    nn.Linear(13, 100),
    nn.ReLU(),
    nn.Linear(100, 50),
    nn.ReLU(),
    nn.Linear(50, 1),
)

model

Sequential(
  (0): Linear(in_features=13, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=50, bias=True)
  (3): ReLU()
  (4): Linear(in_features=50, out_features=1, bias=True)
)

In [78]:
for name, param in model.named_parameters():
    print(f"Name: {name}")
    print(f"Shape: {param.shape}")
    print(f"Values: {param}\n")

Name: 0.weight
Shape: torch.Size([100, 13])
Values: Parameter containing:
tensor([[-0.0251,  0.0909,  0.2697,  ..., -0.1142,  0.2060,  0.1440],
        [ 0.2474,  0.1060, -0.2062,  ...,  0.0548,  0.2571, -0.1074],
        [-0.1489, -0.0154, -0.2140,  ..., -0.1717,  0.1545, -0.0724],
        ...,
        [ 0.1052,  0.0052, -0.2471,  ...,  0.2655,  0.2354, -0.0558],
        [-0.1893,  0.2746,  0.0006,  ..., -0.2732,  0.1313, -0.2499],
        [ 0.0472,  0.0154,  0.2320,  ...,  0.2564, -0.2600, -0.1473]],
       requires_grad=True)

Name: 0.bias
Shape: torch.Size([100])
Values: Parameter containing:
tensor([ 0.2720, -0.0673,  0.0906, -0.0750,  0.2453,  0.2454, -0.0454, -0.0633,
        -0.0148, -0.0405, -0.1227,  0.1558, -0.2725, -0.0855,  0.2045,  0.2120,
        -0.0059,  0.0188,  0.0703, -0.1354,  0.0322,  0.0722,  0.1120, -0.0763,
        -0.2312,  0.2686,  0.1953, -0.1371, -0.2122,  0.2718, -0.0318, -0.0680,
         0.2362, -0.1190,  0.2724, -0.0238, -0.2608, -0.2732, -0.2604,  0.23

In [80]:
optim = Adam(model.parameters(), lr = 0.001)
epochs = 200
criterion = nn.MSELoss()

for epoch in range(epochs):

    optim.zero_grad()
    y_pred = model(X_train)
    loss = criterion(y_pred, y_train.view(-1, 1))
    loss.backward()
    optim.step()

    print('loss: ', loss.item())

loss:  85.87886810302734
loss:  75.40967559814453
loss:  67.30426788330078
loss:  71.0103988647461
loss:  68.38074493408203
loss:  70.65353393554688
loss:  67.3873519897461
loss:  64.38365173339844
loss:  64.6181411743164
loss:  62.95616149902344
loss:  62.18092346191406
loss:  63.564640045166016
loss:  63.151432037353516
loss:  62.185428619384766
loss:  62.37262725830078
loss:  61.5926628112793
loss:  60.23634338378906
loss:  60.15493392944336
loss:  60.1583366394043
loss:  59.6104736328125
loss:  59.75189208984375
loss:  59.909385681152344
loss:  59.26201629638672
loss:  58.839969635009766
loss:  58.737186431884766
loss:  58.20669174194336
loss:  57.84830856323242
loss:  57.98489761352539
loss:  57.850982666015625
loss:  57.6306266784668
loss:  57.600059509277344
loss:  57.30930709838867
loss:  56.93014144897461
loss:  56.810325622558594
loss:  56.62168884277344
loss:  56.40744400024414
loss:  56.36968994140625
loss:  56.19646072387695
loss:  55.93058776855469
loss:  55.7624320983886

In [81]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-0.0665,  0.1112,  0.2402,  ..., -0.1594,  0.1999,  0.0296],
                      [ 0.3573, -0.0038, -0.2997,  ..., -0.1258,  0.2470, -0.3105],
                      [-0.2024, -0.0163, -0.2300,  ..., -0.2167,  0.1550, -0.2023],
                      ...,
                      [-0.0497,  0.0280, -0.1838,  ...,  0.3152,  0.2258,  0.0323],
                      [ 0.0338,  0.3144, -0.1976,  ..., -0.4692,  0.1221, -0.4443],
                      [ 0.0386,  0.0154,  0.2246,  ...,  0.2489, -0.2679, -0.1547]])),
             ('0.bias',
              tensor([ 2.9799e-01, -2.9983e-02,  1.3776e-01, -7.5007e-02,  2.3105e-01,
                       1.8165e-01,  6.6497e-03, -2.3162e-02, -1.4793e-02, -5.9216e-05,
                      -1.1710e-01,  1.6962e-01, -2.5140e-01, -1.2355e-01,  2.3831e-01,
                       2.4879e-01,  5.4847e-02,  5.2901e-02,  1.0145e-01, -1.8847e-01,
                       3.2232e-02,  7.2247e-02,  5.6890e-02, -1.4399

In [84]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [94]:
X_train = X_train.to(device)
y_train = y_train.to(device)
model = model.to(device)

optim = Adam(model.parameters(), lr= 0.001)
epoch = 200
criterion = nn.MSELoss()

for epoch in range(epochs):

    optim.zero_grad()
    y_pred = model(X_train)
    loss = criterion(y_pred, y_train.view(-1, 1))
    loss.backward()
    optim.step()

    print('loss: ', loss.item)

loss:  <built-in method item of Tensor object at 0x0000027806AC0320>
loss:  <built-in method item of Tensor object at 0x0000027806567D40>
loss:  <built-in method item of Tensor object at 0x00000278065FB750>
loss:  <built-in method item of Tensor object at 0x0000027806C67B60>
loss:  <built-in method item of Tensor object at 0x0000027806697110>
loss:  <built-in method item of Tensor object at 0x0000027806A766C0>
loss:  <built-in method item of Tensor object at 0x0000027806567D40>
loss:  <built-in method item of Tensor object at 0x00000278065EF480>
loss:  <built-in method item of Tensor object at 0x0000027806A766C0>
loss:  <built-in method item of Tensor object at 0x0000027806AC0320>
loss:  <built-in method item of Tensor object at 0x00000278065FB750>
loss:  <built-in method item of Tensor object at 0x0000027806A766C0>
loss:  <built-in method item of Tensor object at 0x0000027806C67B60>
loss:  <built-in method item of Tensor object at 0x0000027806697110>
loss:  <built-in method item of Te